
title: "システム工学研究室（高橋グループ）— 豊橋技術科学大学 機械系"
description: "System Engineering Laboratory (Takahashi Group), Department of Mechanical Engineering, Toyohashi University of Technology"
url: "https://tlab-tut.github.io"
baseurl: "/tlab-site"
lang: ja
languages: [ja, en]

theme: minima
minima:
  skin: auto

header_pages:
  - index.md
  - research.md
  - publications.md
  - members.md
  - access.md
  - contact.md
  - en/index.md
  - en/research.md
  - en/publications.md
  - en/members.md
  - en/access.md
  - en/contact.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

lab:
  ja_name: "システム工学研究室（高橋グループ）"
  en_name: "Takahashi Group, System Engineering Laboratory"
  org_line_ja: "豊橋技術科学大学 機械系"
  org_line_en: "Department of Mechanical Engineering, Toyohashi University of Technology"
  email: "takahashi@me.tut.ac.jp"
  address: "〒441-8580 愛知県豊橋市天伯町雲雀ヶ丘1-1 D-405"
  map_link: "https://maps.google.com"
  keywords: ["VGM", "Visual-Geometric Matching", "Digital Twin", "Cleaning Robots", "ROS2", "Indoor Localization"]

github_username: "tlab-tut"
google_analytics: ""
